## Fecthing the data

In [1]:
import pandas as pd

In [2]:
Housing=pd.read_csv('Data.csv')

## Analising Data

In [3]:
Housing.shape

(506, 14)

In [4]:
Housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LISTAT  MEDV  
0  396.90    4.98  24.0  
1  396.90    9.14  21.6  
2  392.83    4.03  34.7  
3  394.63    2.94  33.4  
4  396.90    5.33  36.2

In [5]:
Housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

           LISTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [6]:
Housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LISTAT   506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.4 KB


## Check For UNIQUE

In [7]:
print(Housing['CHAS'].unique())

[0 1]


## Check For NULL

In [8]:
print(Housing.isnull().sum())

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LISTAT     0
MEDV       0
dtype: int64


## Correlation

In [9]:
cor = Housing.corr() 

In [10]:
cor['MEDV'].sort_values(ascending=True)

LISTAT    -0.737663
PTRATIO   -0.507787
INDUS     -0.483725
TAX       -0.468536
NOX       -0.427321
CRIM      -0.388305
RAD       -0.381626
AGE       -0.376955
CHAS       0.175260
DIS        0.249929
B          0.333461
ZN         0.360445
RM         0.695360
MEDV       1.000000
Name: MEDV, dtype: float64

In [11]:
#%matplotlib inline

In [12]:
#import matplotlib.pyplot as plt

In [13]:
#Housing.hist(bins=50 , figsize=(20,15))

## Spliting Train and Test Set

In [14]:
from sklearn.model_selection import train_test_split
Train_set , Test_set = train_test_split(Housing , test_size=0.2 , random_state =40)
print("Row in Train ",len(Train_set),"\nRow in Test",len(Test_set))

Row in Train  404 
Row in Test 102


## Spliting again in different because 'chas' has only two value so to divide the values both in train and test set we have to do stratified shuffle split in accordance with 'chas'

In [15]:
from sklearn.model_selection import StratifiedShuffleSplit
split =StratifiedShuffleSplit(n_splits=1 , test_size=0.2 , random_state=40)
for train , test in split.split(Housing , Housing['CHAS']):
    Train_set = Housing.loc[train]
    Test_set = Housing.loc[test]

In [16]:
Train_set.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
311  0.79041   0.0   9.90     0  0.544  6.122  52.8  2.6403    4  304   
133  0.32982   0.0  21.89     0  0.624  5.822  95.4  2.4699    4  437   
85   0.05735   0.0   4.49     0  0.449  6.630  56.1  4.4377    3  247   
264  0.55007  20.0   3.97     0  0.647  7.206  91.6  1.9301    5  264   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   

     PTRATIO       B  LISTAT  MEDV  
311     18.4  396.90    5.98  22.1  
133     21.2  388.69   15.03  18.4  
85      18.5  392.30    6.53  26.6  
264     13.0  387.89    8.10  36.5  
4       18.7  396.90    5.33  36.2

In [17]:
Test_set.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
72   0.09164   0.0  10.81     0  0.413  6.065   7.8  5.2873    4  305   
19   0.72580   0.0   8.14     0  0.538  5.727  69.5  3.7965    4  307   
165  2.92400   0.0  19.58     0  0.605  6.101  93.0  2.2834    5  403   
60   0.14932  25.0   5.13     0  0.453  5.741  66.2  7.2254    8  284   
261  0.53412  20.0   3.97     0  0.647  7.520  89.4  2.1398    5  264   

     PTRATIO       B  LISTAT  MEDV  
72      19.2  390.91    5.52  22.8  
19      21.0  390.95   11.28  18.2  
165     14.7  240.16    9.81  25.0  
60      19.7  395.11   13.15  18.7  
261     13.0  388.37    7.26  43.1

## Spliting Features and labels

In [18]:
housing_feature = Train_set.drop('MEDV',axis=1)

In [19]:
housing_labels = Train_set['MEDV'].copy()

## Creating pipeline

In [20]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
pipeline = Pipeline ([
    ('imputer',SimpleImputer(strategy= "median")),
    ('scalar',StandardScaler()),
])

In [21]:
housing = pipeline.fit_transform(housing_feature)

In [22]:
housing

array([[-0.33252354, -0.49419439, -0.19419713, ..., -0.02619161,
         0.44336467, -0.96734588],
       [-0.38177342, -0.49419439,  1.53684537, ...,  1.26760532,
         0.35216961,  0.30066882],
       [-0.41090804, -0.49419439, -0.97525967, ...,  0.02001542,
         0.39226878, -0.89028421],
       ...,
       [-0.38714654, -0.49419439, -0.22451564, ...,  0.34346466,
         0.44336467,  0.09890737],
       [-0.41558614,  2.76033506, -1.04600286, ...,  1.22139829,
         0.44336467,  0.26844303],
       [ 1.12681551, -0.49419439,  0.98966846, ...,  0.80553499,
        -1.97302686,  0.9662014 ]])

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

#model = LinearRegression()
#model = DecisionTreeRegressor()
model = RandomForestRegressor()

model.fit(housing,housing_labels)

RandomForestRegressor()

In [24]:
some_data = housing_feature.iloc[:5]

In [25]:
some_labels = housing_labels.iloc[:5]

In [26]:
prepared_data = pipeline.transform(some_data)

In [27]:
model.predict(prepared_data)

array([22.753, 17.973, 27.009, 35.952, 35.39 ])

In [28]:
list(some_labels)

[22.1, 18.4, 26.6, 36.5, 36.2]

In [29]:
import numpy as np
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(model.predict(housing),housing_labels)
rmse = np.sqrt(mse)

In [30]:
rmse

1.3229815430936038

## since rmse is zero we need to apply cross validation

In [31]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(model , housing , housing_labels , scoring='neg_mean_squared_error' ,cv=10)
rmse_score=np.sqrt(-score)

In [32]:
rmse_score

array([4.09455586, 3.97960575, 2.26557909, 4.402058  , 2.31370977,
       2.70324688, 2.87124089, 3.18287926, 4.8920446 , 3.50636841])

In [33]:
def print_score(score):
    print("score = " , score)
    print("mean = " , score.mean())
    print("standard derivation = " , score.std())

In [34]:
print_score(rmse_score)

score =  [4.09455586 3.97960575 2.26557909 4.402058   2.31370977 2.70324688
 2.87124089 3.18287926 4.8920446  3.50636841]
mean =  3.4211288495157133
standard derivation =  0.8564255793699141


## Saving the model

In [35]:
from joblib import dump,load
dump(model , 'Housing Cost.joblib')

['Housing Cost.joblib']

## Testing the model with test set

In [36]:
x_test = Test_set.drop('MEDV',axis=1)

In [37]:
y_test = Test_set['MEDV'].copy()

In [38]:
data_preapred = pipeline.transform(x_test)

In [39]:
final_pridiction = model.predict(data_preapred)

In [40]:
final_mse = mean_squared_error(final_pridiction , y_test)

In [41]:
final_rmse = np.sqrt(final_mse)

In [42]:
final_rmse

3.1366537465091975